-- ---------------------------------------------------------------------------
-- JMail initial schema.
--
-- Conventions:
--   * UUID primary keys, generated by the application so that inserts can be batched.
--   * Email addresses are stored lowercased (see EmailAddresses.canonical) so that
--     equality works without a case-insensitive collation or citext operators.
--   * TIMESTAMPTZ everywhere; the server works exclusively in UTC.
--   * Recipient lists and labels are stored as JSON text: they are always read as a
--     whole with their message, and keeping them inline avoids a fan-out join on the
--     hottest query in the product (the message list).
-- ---------------------------------------------------------------------------

CREATE TABLE users (
    id              UUID PRIMARY KEY,
    email           VARCHAR(320) NOT NULL UNIQUE,
    display_name    VARCHAR(200) NOT NULL,
    avatar_url      VARCHAR(1000),
    locale          VARCHAR(20)  NOT NULL DEFAULT 'en',
    timezone        VARCHAR(64)  NOT NULL DEFAULT 'UTC',
    density         VARCHAR(20)  NOT NULL DEFAULT 'COMFORTABLE',
    theme           VARCHAR(20)  NOT NULL DEFAULT 'SYSTEM',
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    last_login_at   TIMESTAMPTZ,

    CONSTRAINT users_theme_check   CHECK (theme IN ('SYSTEM', 'LIGHT', 'DARK')),
    CONSTRAINT users_density_check CHECK (density IN ('COMPACT', 'COMFORTABLE', 'SPACIOUS'))
);

-- ---------------------------------------------------------------------------
-- Linked mailboxes. One user can connect any number of accounts across providers.
-- ---------------------------------------------------------------------------
CREATE TABLE mail_accounts (
    id                      UUID PRIMARY KEY,
    user_id                 UUID         NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    provider                VARCHAR(32)  NOT NULL,
    provider_account_id     VARCHAR(255) NOT NULL,
    email                   VARCHAR(320) NOT NULL,
    display_name            VARCHAR(200) NOT NULL,
    avatar_url              VARCHAR(1000),

    -- OAuth material (encrypted at rest by the application, never logged).
    access_token            TEXT,
    refresh_token           TEXT,
    token_expires_at        TIMESTAMPTZ,
    scopes                  TEXT,

    -- Credential material for on-premises Exchange / generic IMAP accounts.
    imap_host               VARCHAR(255),
    imap_port               INTEGER,
    smtp_host               VARCHAR(255),
    smtp_port               INTEGER,
    ews_url                 VARCHAR(1000),
    username                VARCHAR(255),
    password_secret         TEXT,
    use_tls                 BOOLEAN      NOT NULL DEFAULT TRUE,

    status                  VARCHAR(32)  NOT NULL DEFAULT 'CONNECTED',
    status_detail           VARCHAR(500),
    is_primary              BOOLEAN      NOT NULL DEFAULT FALSE,
    color                   VARCHAR(9),
    last_sync_at            TIMESTAMPTZ,
    sync_cursor             VARCHAR(500),
    created_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT mail_accounts_provider_check
        CHECK (provider IN ('GOOGLE', 'MICROSOFT', 'APPLE', 'EXCHANGE', 'IMAP', 'DEMO')),
    CONSTRAINT mail_accounts_status_check
        CHECK (status IN ('CONNECTED', 'REAUTH_REQUIRED', 'SYNCING', 'ERROR', 'DISABLED')),
    CONSTRAINT mail_accounts_unique_per_user
        UNIQUE (user_id, provider, provider_account_id)
);

CREATE INDEX idx_mail_accounts_user ON mail_accounts (user_id);
CREATE INDEX idx_mail_accounts_sync ON mail_accounts (status, last_sync_at)
    WHERE status IN ('CONNECTED', 'SYNCING');

-- ---------------------------------------------------------------------------
-- Refresh tokens. Only the SHA-256 hash is stored, so a database leak cannot be
-- replayed against the API.
-- ---------------------------------------------------------------------------
CREATE TABLE refresh_tokens (
    id            UUID PRIMARY KEY,
    user_id       UUID         NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash    VARCHAR(64)  NOT NULL UNIQUE,
    issued_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    expires_at    TIMESTAMPTZ  NOT NULL,
    revoked_at    TIMESTAMPTZ,
    replaced_by   UUID,
    user_agent    VARCHAR(500),
    client_ip     VARCHAR(64)
);

CREATE INDEX idx_refresh_tokens_user ON refresh_tokens (user_id, expires_at DESC);

-- ---------------------------------------------------------------------------
-- Categories: the organising principle of the JMail inbox. System categories are
-- shared (user_id IS NULL); users may add their own and reorder everything.
-- ---------------------------------------------------------------------------
CREATE TABLE categories (
    id            UUID PRIMARY KEY,
    user_id       UUID REFERENCES users (id) ON DELETE CASCADE,
    key           VARCHAR(64)  NOT NULL,
    name          VARCHAR(100) NOT NULL,
    description   VARCHAR(300),
    color         VARCHAR(9)   NOT NULL DEFAULT '#4F46E5',
    icon          VARCHAR(64)  NOT NULL DEFAULT 'inbox',
    position      INTEGER      NOT NULL DEFAULT 0,
    is_system     BOOLEAN      NOT NULL DEFAULT FALSE,
    is_enabled    BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- Two partial unique indexes rather than one constraint: NULL user_id (system rows)
-- would otherwise never collide, allowing duplicate system keys.
CREATE UNIQUE INDEX uq_categories_system_key ON categories (key) WHERE user_id IS NULL;
CREATE UNIQUE INDEX uq_categories_user_key   ON categories (user_id, key) WHERE user_id IS NOT NULL;
CREATE INDEX idx_categories_user_position    ON categories (user_id, position);

CREATE TABLE category_rules (
    id            UUID PRIMARY KEY,
    category_id   UUID         NOT NULL REFERENCES categories (id) ON DELETE CASCADE,
    field         VARCHAR(32)  NOT NULL,
    operation     VARCHAR(32)  NOT NULL,
    value         VARCHAR(500) NOT NULL,
    weight        INTEGER      NOT NULL DEFAULT 10,
    is_enabled    BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT category_rules_field_check
        CHECK (field IN ('SENDER', 'SENDER_DOMAIN', 'SUBJECT', 'BODY', 'LIST_ID', 'HEADER', 'RECIPIENT')),
    CONSTRAINT category_rules_operation_check
        CHECK (operation IN ('CONTAINS', 'EQUALS', 'STARTS_WITH', 'ENDS_WITH', 'REGEX')),
    CONSTRAINT category_rules_weight_check CHECK (weight BETWEEN 1 AND 100)
);

CREATE INDEX idx_category_rules_category ON category_rules (category_id) WHERE is_enabled;

-- ---------------------------------------------------------------------------
-- Folders mirror the provider's own hierarchy so that actions round-trip.
-- ---------------------------------------------------------------------------
CREATE TABLE folders (
    id            UUID PRIMARY KEY,
    account_id    UUID         NOT NULL REFERENCES mail_accounts (id) ON DELETE CASCADE,
    remote_id     VARCHAR(500) NOT NULL,
    name          VARCHAR(255) NOT NULL,
    path          VARCHAR(1000) NOT NULL,
    type          VARCHAR(32)  NOT NULL DEFAULT 'CUSTOM',
    parent_id     UUID REFERENCES folders (id) ON DELETE CASCADE,
    unread_count  INTEGER      NOT NULL DEFAULT 0,
    total_count   INTEGER      NOT NULL DEFAULT 0,
    position      INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT folders_type_check
        CHECK (type IN ('INBOX', 'SENT', 'DRAFTS', 'ARCHIVE', 'SPAM', 'TRASH', 'SCHEDULED', 'CUSTOM')),
    CONSTRAINT folders_unique_remote UNIQUE (account_id, remote_id)
);

CREATE INDEX idx_folders_account ON folders (account_id, position);

-- ---------------------------------------------------------------------------
-- Messages. The message list is the hottest read path in the product, so this table
-- carries denormalised snippet/sender columns and a generated search vector.
-- ---------------------------------------------------------------------------
CREATE TABLE messages (
    id                  UUID PRIMARY KEY,
    account_id          UUID         NOT NULL REFERENCES mail_accounts (id) ON DELETE CASCADE,
    folder_id           UUID         NOT NULL REFERENCES folders (id) ON DELETE CASCADE,
    category_id         UUID REFERENCES categories (id) ON DELETE SET NULL,

    remote_id           VARCHAR(500) NOT NULL,
    thread_id           VARCHAR(500) NOT NULL,
    message_id_header   VARCHAR(998),
    in_reply_to         VARCHAR(998),
    list_id             VARCHAR(500),

    subject             VARCHAR(2000) NOT NULL DEFAULT '',
    snippet             VARCHAR(500)  NOT NULL DEFAULT '',
    body_text           TEXT,
    body_html           TEXT,

    from_address        VARCHAR(320) NOT NULL,
    from_name           VARCHAR(300) NOT NULL DEFAULT '',
    to_recipients       TEXT         NOT NULL DEFAULT '[]',
    cc_recipients       TEXT         NOT NULL DEFAULT '[]',
    bcc_recipients      TEXT         NOT NULL DEFAULT '[]',
    reply_to            VARCHAR(320),

    sent_at             TIMESTAMPTZ  NOT NULL,
    received_at         TIMESTAMPTZ  NOT NULL,

    is_read             BOOLEAN      NOT NULL DEFAULT FALSE,
    is_starred          BOOLEAN      NOT NULL DEFAULT FALSE,
    is_important        BOOLEAN      NOT NULL DEFAULT FALSE,
    is_draft            BOOLEAN      NOT NULL DEFAULT FALSE,
    is_archived         BOOLEAN      NOT NULL DEFAULT FALSE,
    is_trashed          BOOLEAN      NOT NULL DEFAULT FALSE,
    is_spam             BOOLEAN      NOT NULL DEFAULT FALSE,
    has_attachments     BOOLEAN      NOT NULL DEFAULT FALSE,

    size_bytes          BIGINT       NOT NULL DEFAULT 0,
    labels              TEXT         NOT NULL DEFAULT '[]',
    category_confidence REAL         NOT NULL DEFAULT 0,
    category_pinned     BOOLEAN      NOT NULL DEFAULT FALSE,

    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),

    search_vector       TSVECTOR GENERATED ALWAYS AS (
        setweight(to_tsvector('english', coalesce(subject, '')), 'A') ||
        setweight(to_tsvector('english', coalesce(from_name, '') || ' ' || coalesce(from_address, '')), 'B') ||
        setweight(to_tsvector('english', coalesce(body_text, '')), 'C')
    ) STORED,

    CONSTRAINT messages_unique_remote UNIQUE (account_id, remote_id)
);

-- The default list query: one account's inbox, newest first, excluding trash/spam.
CREATE INDEX idx_messages_account_received ON messages (account_id, received_at DESC);
CREATE INDEX idx_messages_folder_received  ON messages (folder_id, received_at DESC);
CREATE INDEX idx_messages_thread           ON messages (thread_id, received_at);
CREATE INDEX idx_messages_category         ON messages (category_id, received_at DESC);
CREATE INDEX idx_messages_unread           ON messages (account_id, received_at DESC) WHERE NOT is_read;
CREATE INDEX idx_messages_starred          ON messages (account_id, received_at DESC) WHERE is_starred;
CREATE INDEX idx_messages_search           ON messages USING GIN (search_vector);
-- Trigram index backs the "contains" fallback used for substring matches that
-- stemmed full-text search misses (order numbers, partial addresses).
CREATE INDEX idx_messages_subject_trgm     ON messages USING GIN (subject gin_trgm_ops);
CREATE INDEX idx_messages_from_trgm        ON messages USING GIN (from_address gin_trgm_ops);

CREATE TABLE attachments (
    id            UUID PRIMARY KEY,
    message_id    UUID         NOT NULL REFERENCES messages (id) ON DELETE CASCADE,
    remote_id     VARCHAR(500),
    filename      VARCHAR(500) NOT NULL,
    mime_type     VARCHAR(255) NOT NULL DEFAULT 'application/octet-stream',
    size_bytes    BIGINT       NOT NULL DEFAULT 0,
    content_id    VARCHAR(255),
    is_inline     BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX idx_attachments_message ON attachments (message_id);

-- ---------------------------------------------------------------------------
-- Bookkeeping for incremental sync runs; also what the UI's "last updated" reads.
-- ---------------------------------------------------------------------------
CREATE TABLE sync_runs (
    id              UUID PRIMARY KEY,
    account_id      UUID        NOT NULL REFERENCES mail_accounts (id) ON DELETE CASCADE,
    started_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at     TIMESTAMPTZ,
    status          VARCHAR(32) NOT NULL DEFAULT 'RUNNING',
    messages_added  INTEGER     NOT NULL DEFAULT 0,
    messages_updated INTEGER    NOT NULL DEFAULT 0,
    error_message   VARCHAR(2000),

    CONSTRAINT sync_runs_status_check CHECK (status IN ('RUNNING', 'SUCCEEDED', 'FAILED'))
);

CREATE INDEX idx_sync_runs_account ON sync_runs (account_id, started_at DESC);
